stages:
  - build
  - release
  - deploy

variables:
  PROD_KUBECONFIG: prod-kubeconfig.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH

  # this part generate the docker images for test and production
testing:
  stage: build
  image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
  tags:
      - startfleet
  script:
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
      - tags

release:
  stage: release
  image: node:12
  script:
  - npx -p semantic-release-gitmoji -p semantic-release -p @semantic-release/gitlab -p @semantic-release/git semantic-release
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

production:
  stage: build
  image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
  tags:
      - startfleet
  script:
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --build-arg ENVIRONMENT=production --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
      - tags

# This part deploys Armadacar to production
deploy:
  stage: deploy
  image: registry.gitlab.com/startfleet/gitlab-runner:master
  tags:
      - startfleet
  script:
      - echo $KUBECONFIG | base64 -d | cat $2 > $PROD_KUBECONFIG
      - export KUBECONFIG=$PROD_KUBECONFIG
      - kubectl set image deployment.v1.apps/api-user-deployment user-api=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --record -n user-api
      - kubectl -n user-api rollout status deployment/api-user-deployment
  only:
      - tags